"use client";
import Image from "next/image";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { useLMS } from "@/lib/store";
import { BarChart3, BookOpen, FolderOpen, GraduationCap, History, LayoutDashboard, Layers, Settings, ShieldCheck, TrendingUp, Users, Video } from "lucide-react";
import { cn } from "@/lib/utils";
interface AppSidebarProps { onCloseMobile?: () => void }
const teacher=[["Dashboard","/teacher/dashboard",LayoutDashboard],["Students","/teacher/students",Users],["Sessions","/teacher/sessions",Video],["Whiteboards","/teacher/whiteboards",Layers],["Assignments","/teacher/assignments",BookOpen],["Materials","/teacher/materials",FolderOpen],["History","/teacher/history",History],["Reports","/teacher/reports",BarChart3],["Settings","/teacher/settings",Settings]] as const;
const student=[["Home","/student/dashboard",LayoutDashboard],["Sessions","/student/sessions",Video],["Whiteboards","/student/whiteboards",Layers],["Assignments","/student/assignments",BookOpen],["Materials","/student/materials",FolderOpen],["Progress","/student/progress",TrendingUp],["History","/student/history",History],["Settings","/student/settings",Settings]] as const;
const admin=[["Dashboard","/admin/dashboard",LayoutDashboard],["Teachers","/admin/teachers",GraduationCap],["Students","/admin/students",Users],["Sessions","/admin/sessions",Video],["Assignments","/admin/assignments",BookOpen],["Materials","/admin/materials",FolderOpen],["Reports","/admin/reports",BarChart3],["Settings","/admin/settings",Settings]] as const;
export function AppSidebar({onCloseMobile}:AppSidebarProps){const path=usePathname();const{role}=useLMS();const items=role==="TEACHER"?teacher:role==="STUDENT"?student:admin;return <aside className="w-72 h-full flex flex-col rounded-xl bg-[#f8f9ff]/80 backdrop-blur-xl shadow-[0_2px_12px_rgba(32,48,75,.04)] overflow-hidden"><Link href="/" className="h-24 px-7 flex items-center"><Image src="/icon.jpg" alt="Sofia Systems" width={92} height={42} className="w-[92px] h-auto object-contain" priority/></Link><nav className="flex-1 overflow-y-auto px-5 py-1 space-y-2">{items.map(([label,href,Icon])=>{const active=path===href||(href.split('/').length>3&&path.startsWith(href));return <Link key={href} href={href} onClick={onCloseMobile} className={cn("h-14 px-5 rounded-lg flex items-center gap-5 text-[15px] font-medium transition-colors",active?"bg-[#6063ee] text-white font-semibold":"text-[#464554] hover:bg-[#e5eeff] hover:text-[#0b1c30]")}><Icon className="w-5 h-5"/><span>{label}</span></Link>})}</nav>{role==="TEACHER"&&<Link href="/manage" className="mx-5 mb-5 h-14 px-5 rounded-lg flex items-center gap-5 text-[15px] text-[#464554] hover:bg-[#e5eeff]"><ShieldCheck className="w-5 h-5"/>Admin</Link>}</aside>}
