import {
  User,
  Teacher,
  Student,
  Subject,
  Session,
  Whiteboard,
  Assignment,
  Submission,
  StudyMaterial,
  SessionReport,
  Notification,
} from "@/types";

export const mockUsers: Record<string, User> = {
  teacher: {
    id: "t1",
    name: "Alex Thomas",
    email: "alex.thomas@edulearn.io",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    role: "TEACHER",
    title: "Senior 1-on-1 Mathematics & Physics Educator",
    phone: "+1 (555) 234-5678",
    timezone: "UTC-5 (EST)",
    bio: "Passionate about personalized one-on-one STEM instruction. 8+ years helping high schoolers crack calculus and mechanics.",
  },
  student: {
    id: "s1",
    name: "Rahul Menon",
    email: "rahul.menon@student.io",
    avatar: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80",
    role: "STUDENT",
    title: "Grade 11 STEM Student",
    phone: "+1 (555) 876-5432",
    timezone: "UTC-5 (EST)",
    bio: "Focusing on AP Calculus and Advanced Physics for upcoming engineering entrance.",
  },
  admin: {
    id: "adm1",
    name: "Eleanor Vance",
    email: "admin@edulearn.io",
    avatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80",
    role: "SUPERADMIN",
    title: "Platform Super Administrator",
    phone: "+1 (555) 999-0000",
    timezone: "UTC-5 (EST)",
  },
};

export const mockTeachers: Teacher[] = [
  {
    id: "t1",
    name: "Alex Thomas",
    email: "alex.thomas@edulearn.io",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    subjects: ["Mathematics", "Physics"],
    rating: 4.95,
    totalStudents: 4,
    totalSessions: 148,
    status: "active",
    joinedDate: "2024-01-15",
  },
  {
    id: "t2",
    name: "Sarah Joseph",
    email: "sarah.joseph@edulearn.io",
    avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
    subjects: ["Chemistry", "Computer Science"],
    rating: 4.9,
    totalStudents: 3,
    totalSessions: 112,
    status: "active",
    joinedDate: "2024-03-01",
  },
];

export const mockStudents: Student[] = [
  {
    id: "s1",
    name: "Rahul Menon",
    email: "rahul.menon@student.io",
    avatar: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80",
    grade: "Grade 11",
    subjects: ["Mathematics", "Physics"],
    teacherId: "t1",
    teacherName: "Alex Thomas",
    overallProgress: 72,
    lastSessionDate: "2026-08-27",
    nextSessionDate: "2026-08-29",
    nextSessionTime: "04:00 PM",
    pendingAssignmentsCount: 1,
    status: "active",
    joinedDate: "2024-02-10",
    attendanceRate: 96,
    notes: "Excelling in quadratic functions. Needs extra reinforcement with polynomial roots.",
  },
  {
    id: "s2",
    name: "Ananya Nair",
    email: "ananya.nair@student.io",
    avatar: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80",
    grade: "Grade 10",
    subjects: ["Mathematics", "Physics"],
    teacherId: "t1",
    teacherName: "Alex Thomas",
    overallProgress: 84,
    lastSessionDate: "2026-08-28",
    nextSessionDate: "2026-08-30",
    nextSessionTime: "11:30 AM",
    pendingAssignmentsCount: 0,
    status: "active",
    joinedDate: "2024-01-20",
    attendanceRate: 100,
    notes: "Consistently completes homework early. Working on physics kinematics vectors.",
  },
  {
    id: "s3",
    name: "Arjun Kumar",
    email: "arjun.kumar@student.io",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    grade: "Grade 12",
    subjects: ["Mathematics", "Computer Science"],
    teacherId: "t1",
    teacherName: "Alex Thomas",
    overallProgress: 65,
    lastSessionDate: "2026-08-26",
    nextSessionDate: "2026-08-31",
    nextSessionTime: "02:00 PM",
    pendingAssignmentsCount: 2,
    status: "active",
    joinedDate: "2024-04-05",
    attendanceRate: 88,
    notes: "Strong logic skills in CS, working on Calculus integration techniques.",
  },
  {
    id: "s4",
    name: "Meera Thomas",
    email: "meera.thomas@student.io",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80",
    grade: "Grade 9",
    subjects: ["Mathematics", "Physics"],
    teacherId: "t1",
    teacherName: "Alex Thomas",
    overallProgress: 91,
    lastSessionDate: "2026-08-25",
    nextSessionDate: "2026-09-01",
    nextSessionTime: "05:00 PM",
    pendingAssignmentsCount: 0,
    status: "active",
    joinedDate: "2024-05-12",
    attendanceRate: 98,
    notes: "High enthusiasm in geometry and algebraic transformations.",
  },
];

export const mockSubjects: Subject[] = [
  {
    id: "sub-math",
    name: "Mathematics",
    code: "MATH",
    color: "#4f46e5",
    icon: "Calculator",
    description: "Algebra, Geometry, Trigonometry, Calculus & Polynomials",
    studentCount: 4,
    topics: ["Quadratic Equations", "Derivatives", "Linear Algebra", "Trigonometric Identities", "Complex Numbers"],
  },
  {
    id: "sub-phys",
    name: "Physics",
    code: "PHYS",
    color: "#0284c7",
    icon: "Atom",
    description: "Classical Mechanics, Kinematics, Thermodynamics & Electromagnetism",
    studentCount: 3,
    topics: ["Newton's Laws of Motion", "Kinematics 1D & 2D", "Work, Energy & Power", "Circular Motion", "Optics"],
  },
  {
    id: "sub-chem",
    name: "Chemistry",
    code: "CHEM",
    color: "#059669",
    icon: "FlaskConical",
    description: "Organic Chemistry, Stoichiometry, Molecular Structure & Chemical Equilibrium",
    studentCount: 2,
    topics: ["Chemical Bonding", "Organic Reaction Mechanisms", "Electrochemistry", "Periodic Properties"],
  },
  {
    id: "sub-cs",
    name: "Computer Science",
    code: "CS",
    color: "#7c3aed",
    icon: "Code",
    description: "Data Structures, Algorithms, Python Programming & Computational Problem Solving",
    studentCount: 2,
    topics: ["Object-Oriented Programming", "Array & Linked Lists", "Recursion", "Binary Search & Sorting"],
  },
];

export const mockSessions: Session[] = [
  {
    id: "sess-101",
    teacherId: "t1",
    teacherName: "Alex Thomas",
    teacherAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    studentId: "s1",
    studentName: "Rahul Menon",
    studentAvatar: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80",
    subject: "Mathematics",
    topic: "Quadratic Equations — Roots & Factorisation",
    date: "2026-08-29",
    scheduledTime: "04:00 PM",
    durationMinutes: 60,
    status: "SCHEDULED",
    whiteboardId: "wb-live-math-rahul",
    notes: "Review question 3 from yesterday's homework and introduce quadratic formula derivation.",
  },
  {
    id: "sess-102",
    teacherId: "t1",
    teacherName: "Alex Thomas",
    teacherAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    studentId: "s2",
    studentName: "Ananya Nair",
    studentAvatar: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80",
    subject: "Physics",
    topic: "Newton's Second Law & Friction Forces",
    date: "2026-08-30",
    scheduledTime: "11:30 AM",
    durationMinutes: 45,
    status: "SCHEDULED",
    whiteboardId: "wb-live-phys-ananya",
    notes: "Solve incline plane problems with static and kinetic friction coefficients.",
  },
  {
    id: "sess-103",
    teacherId: "t1",
    teacherName: "Alex Thomas",
    teacherAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    studentId: "s3",
    studentName: "Arjun Kumar",
    studentAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    subject: "Mathematics",
    topic: "Calculus — Chain Rule & Product Rule Practice",
    date: "2026-08-27",
    scheduledTime: "02:00 PM",
    durationMinutes: 52,
    status: "COMPLETED",
    actualStartTime: "14:00",
    actualEndTime: "14:52",
    actualDurationSeconds: 3120,
    whiteboardId: "wb-hist-arjun-calc",
    reportId: "rep-201",
    notes: "Deep dive on trigonometric derivative substitutions.",
    assignmentSummary: "Assigned 6 derivative problems for weekend review.",
  },
  {
    id: "sess-104",
    teacherId: "t1",
    teacherName: "Alex Thomas",
    teacherAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    studentId: "s4",
    studentName: "Meera Thomas",
    studentAvatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80",
    subject: "Mathematics",
    topic: "Linear Inequalities & Coordinate Geometry",
    date: "2026-08-25",
    scheduledTime: "05:00 PM",
    durationMinutes: 50,
    status: "COMPLETED",
    actualStartTime: "17:00",
    actualEndTime: "17:50",
    actualDurationSeconds: 3000,
    whiteboardId: "wb-hist-meera-geom",
    reportId: "rep-202",
  },
];

export const mockWhiteboards: Whiteboard[] = [
  {
    id: "wb-live-math-rahul",
    title: "Mathematics — Quadratic Equations Live Board",
    subject: "Mathematics",
    studentId: "s1",
    studentName: "Rahul Menon",
    teacherId: "t1",
    category: "LIVE_CLASS",
    lastEdited: "2026-08-29T10:30:00Z",
    elements: [
      {
        id: "el-1",
        type: "text",
        x: 80,
        y: 60,
        text: "🎯 Topic: Quadratic Equations (Ax² + Bx + C = 0)",
        strokeColor: "#1e293b",
        strokeWidth: 2,
        fontSize: 22,
      },
      {
        id: "el-2",
        type: "sticky",
        x: 80,
        y: 110,
        text: "Standard Formula:\nx = (-b ± √(b² - 4ac)) / (2a)",
        strokeColor: "#f59e0b",
        fillColor: "#fef3c7",
        strokeWidth: 1,
        width: 280,
        height: 120,
      },
      {
        id: "el-3",
        type: "text",
        x: 420,
        y: 120,
        text: "Example Problem 1: Solve 2x² - 8x + 6 = 0",
        strokeColor: "#334155",
        strokeWidth: 2,
        fontSize: 18,
      },
      {
        id: "el-4",
        type: "pen",
        x: 420,
        y: 160,
        points: [
          { x: 420, y: 170 },
          { x: 450, y: 172 },
          { x: 500, y: 171 },
          { x: 560, y: 175 },
        ],
        strokeColor: "#4f46e5",
        strokeWidth: 3,
      },
      {
        id: "el-5",
        type: "text",
        x: 420,
        y: 200,
        text: "Step 1: Divide by 2 => x² - 4x + 3 = 0\nStep 2: Factorise => (x - 3)(x - 1) = 0\nRoots: x = 3, x = 1",
        strokeColor: "#0f766e",
        strokeWidth: 2,
        fontSize: 16,
      },
      {
        id: "el-6",
        type: "stamp",
        x: 720,
        y: 210,
        stampType: "correct",
        strokeColor: "#16a34a",
        strokeWidth: 2,
      },
    ],
  },
  {
    id: "wb-rahul-math-hw",
    title: "Mathematics — Algebra Homework",
    subject: "Mathematics",
    studentId: "s1",
    studentName: "Rahul Menon",
    teacherId: "t1",
    category: "ASSIGNMENTS",
    lastEdited: "2026-08-28T19:45:00Z",
    elements: [
      {
        id: "q-1",
        type: "question_card",
        x: 60,
        y: 60,
        questionNumber: 1,
        questionText: "Solve for x:  3x² - 12x + 9 = 0",
        strokeColor: "#3b82f6",
        strokeWidth: 1,
        width: 400,
        height: 100,
      },
      {
        id: "q-1-ans",
        type: "text",
        x: 70,
        y: 180,
        text: "Rahul's solution:\n3(x² - 4x + 3) = 0\n(x - 3)(x - 1) = 0\nx = 3 or x = 1",
        strokeColor: "#1e293b",
        strokeWidth: 2,
        fontSize: 16,
      },
      {
        id: "q-1-stamp",
        type: "stamp",
        x: 340,
        y: 190,
        stampType: "correct",
        strokeColor: "#16a34a",
        strokeWidth: 2,
      },
      {
        id: "q-2",
        type: "question_card",
        x: 60,
        y: 280,
        questionNumber: 2,
        questionText: "Find the vertex of the parabola: y = -2x² + 8x - 5",
        strokeColor: "#3b82f6",
        strokeWidth: 1,
        width: 400,
        height: 100,
      },
      {
        id: "q-2-ans",
        type: "text",
        x: 70,
        y: 400,
        text: "x_v = -b/(2a) = -8 / (-4) = 2\ny_v = -2(2)² + 8(2) - 5 = -8 + 16 - 5 = 3\nVertex = (2, 3)",
        strokeColor: "#1e293b",
        strokeWidth: 2,
        fontSize: 16,
      },
      {
        id: "q-2-stamp",
        type: "stamp",
        x: 340,
        y: 410,
        stampType: "correct",
        strokeColor: "#16a34a",
        strokeWidth: 2,
      },
    ],
  },
  {
    id: "wb-rahul-math-practice",
    title: "Mathematics — Quadratic Practice Scratchpad",
    subject: "Mathematics",
    studentId: "s1",
    studentName: "Rahul Menon",
    category: "PRACTICE",
    lastEdited: "2026-08-29T08:15:00Z",
    elements: [
      {
        id: "p-1",
        type: "text",
        x: 80,
        y: 80,
        text: "My practice notes on Discriminant:\nΔ = b² - 4ac\nIf Δ > 0 => 2 distinct real roots\nIf Δ = 0 => 1 repeated root\nIf Δ < 0 => 2 complex conjugate roots",
        strokeColor: "#475569",
        strokeWidth: 2,
        fontSize: 16,
      },
    ],
  },
  {
    id: "wb-rahul-phys-hw",
    title: "Physics — Mechanics & Free Body Diagrams",
    subject: "Physics",
    studentId: "s1",
    studentName: "Rahul Menon",
    teacherId: "t1",
    category: "ASSIGNMENTS",
    lastEdited: "2026-08-27T16:20:00Z",
    elements: [
      {
        id: "phys-q1",
        type: "question_card",
        x: 60,
        y: 60,
        questionNumber: 1,
        questionText: "Draw a Free Body Diagram for a 5kg block on a 30° incline with friction μ = 0.2",
        strokeColor: "#0284c7",
        strokeWidth: 1,
        width: 480,
        height: 100,
      },
      {
        id: "phys-arrow-1",
        type: "arrow",
        x: 150,
        y: 220,
        points: [{ x: 150, y: 220 }, { x: 150, y: 320 }],
        strokeColor: "#dc2626",
        strokeWidth: 3,
      },
      {
        id: "phys-label-mg",
        type: "text",
        x: 160,
        y: 310,
        text: "mg = 49 N",
        strokeColor: "#dc2626",
        strokeWidth: 2,
        fontSize: 14,
      },
    ],
  },
  {
    id: "wb-ananya-math-practice",
    title: "Mathematics — Geometry Proofs",
    subject: "Mathematics",
    studentId: "s2",
    studentName: "Ananya Nair",
    category: "PRACTICE",
    lastEdited: "2026-08-28T14:10:00Z",
    elements: [
      {
        id: "geom-1",
        type: "text",
        x: 80,
        y: 80,
        text: "Theorem: Inscribed angle subtended by diameter is 90°",
        strokeColor: "#1e293b",
        strokeWidth: 2,
        fontSize: 18,
      },
      {
        id: "geom-circle",
        type: "circle",
        x: 100,
        y: 140,
        width: 180,
        height: 180,
        strokeColor: "#4f46e5",
        strokeWidth: 2,
      },
    ],
  },
  {
    id: "wb-arjun-cs-practice",
    title: "Computer Science — Binary Tree Traversal",
    subject: "Computer Science",
    studentId: "s3",
    studentName: "Arjun Kumar",
    category: "MY_WORK",
    lastEdited: "2026-08-26T11:00:00Z",
    elements: [
      {
        id: "cs-1",
        type: "text",
        x: 80,
        y: 80,
        text: "In-order Traversal: Left -> Root -> Right\nPre-order: Root -> Left -> Right\nPost-order: Left -> Right -> Root",
        strokeColor: "#7c3aed",
        strokeWidth: 2,
        fontSize: 16,
      },
    ],
  },
];

export const mockAssignments: Assignment[] = [
  {
    id: "asg-1",
    title: "Quadratic Equations Mastery & Problem Solving",
    subject: "Mathematics",
    teacherId: "t1",
    teacherName: "Alex Thomas",
    description: "Solve factorisation, quadratic formula derivations, and real-world trajectory problem.",
    dueDate: "2026-08-30",
    dueTime: "11:59 PM",
    difficulty: "Medium",
    instructions: "Write full calculation steps on the whiteboard canvas. Clearly state values of a, b, c.",
    targetType: "MULTIPLE",
    assignedStudentIds: ["s1", "s2"],
    questions: [
      {
        id: "q1",
        number: 1,
        text: "Solve by factorisation: 2x² - 8x + 6 = 0",
        maxScore: 4,
        subject: "Mathematics",
      },
      {
        id: "q2",
        number: 2,
        text: "Find the discriminant and describe the roots of: x² + 4x + 5 = 0",
        maxScore: 3,
        subject: "Mathematics",
      },
      {
        id: "q3",
        number: 3,
        text: "A projectile's height is given by h(t) = -5t² + 20t + 25. Find the maximum height and time to hit the ground.",
        maxScore: 5,
        subject: "Mathematics",
      },
    ],
    whiteboardId: "wb-asg-quad-questions",
    createdAt: "2026-08-28",
    submissionsCount: 2,
    reviewedCount: 1,
  },
  {
    id: "asg-2",
    title: "Newton's Laws & Incline Plane Dynamics",
    subject: "Physics",
    teacherId: "t1",
    teacherName: "Alex Thomas",
    description: "Free body diagrams, normal force resolution, and coefficient of kinetic friction calculations.",
    dueDate: "2026-09-02",
    dueTime: "06:00 PM",
    difficulty: "Hard",
    instructions: "Draw labeled force vectors on the canvas before computing algebraic formulas.",
    targetType: "INDIVIDUAL",
    assignedStudentIds: ["s1"],
    questions: [
      {
        id: "pq1",
        number: 1,
        text: "A 10 kg crate rests on a 30° incline. If μ_s = 0.4, determine if the block slides.",
        maxScore: 5,
        subject: "Physics",
      },
      {
        id: "pq2",
        number: 2,
        text: "Calculate the acceleration down the incline if μ_k = 0.25.",
        maxScore: 5,
        subject: "Physics",
      },
    ],
    createdAt: "2026-08-27",
    submissionsCount: 0,
    reviewedCount: 0,
  },
  {
    id: "asg-3",
    title: "Calculus — Chain Rule & Product Rule Worksheet",
    subject: "Mathematics",
    teacherId: "t1",
    teacherName: "Alex Thomas",
    description: "Differentiate composite exponential, logarithmic, and trigonometric functions.",
    dueDate: "2026-08-28",
    dueTime: "11:59 PM",
    difficulty: "Medium",
    instructions: "Express answers in simplest factored form.",
    targetType: "BROADCAST",
    assignedStudentIds: ["s1", "s2", "s3", "s4"],
    questions: [
      {
        id: "cq1",
        number: 1,
        text: "Find f'(x) for f(x) = (3x² - 5)⁴",
        maxScore: 4,
        subject: "Mathematics",
      },
      {
        id: "cq2",
        number: 2,
        text: "Find dy/dx for y = x³ · sin(2x)",
        maxScore: 4,
        subject: "Mathematics",
      },
    ],
    createdAt: "2026-08-25",
    submissionsCount: 4,
    reviewedCount: 4,
  },
];

export const mockSubmissions: Submission[] = [
  {
    id: "subm-1",
    assignmentId: "asg-1",
    assignmentTitle: "Quadratic Equations Mastery & Problem Solving",
    studentId: "s1",
    studentName: "Rahul Menon",
    studentAvatar: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80",
    subject: "Mathematics",
    submittedAt: "2026-08-28T20:15:00Z",
    status: "REVIEWED",
    score: 11,
    maxScore: 12,
    teacherFeedback: "Excellent work on Questions 1 and 2! In Question 3, remember to discard the negative time root t = -1 when computing ground impact. Superb layout on the whiteboard!",
    questionMarks: {
      q1: { status: "correct", marks: 4, comment: "Accurate factorisation!" },
      q2: { status: "correct", marks: 3, comment: "Discriminant Δ = -4, complex roots correct." },
      q3: { status: "partial", marks: 4, comment: "Max height (45m at t=2s) correct. Minor note on ground impact notation." },
    },
    whiteboardId: "wb-rahul-math-hw",
  },
  {
    id: "subm-2",
    assignmentId: "asg-1",
    assignmentTitle: "Quadratic Equations Mastery & Problem Solving",
    studentId: "s2",
    studentName: "Ananya Nair",
    studentAvatar: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80",
    subject: "Mathematics",
    submittedAt: "2026-08-29T09:30:00Z",
    status: "SUBMITTED",
    maxScore: 12,
    whiteboardId: "wb-ananya-math-practice",
  },
];

export const mockMaterials: StudyMaterial[] = [
  {
    id: "mat-1",
    title: "Quadratic Functions & Parabola Properties (Comprehensive Notes)",
    subject: "Mathematics",
    type: "PDF",
    size: "2.4 MB",
    uploadDate: "2026-08-24",
    url: "#",
    description: "Detailed summary of vertex formulas, axis of symmetry, discriminant charts, and standard transforms.",
    assignedTo: "ALL",
    downloadsCount: 18,
  },
  {
    id: "mat-2",
    title: "Mastering Incline Planes & Friction Vectors (Video Walkthrough)",
    subject: "Physics",
    type: "VIDEO",
    size: "48.2 MB",
    uploadDate: "2026-08-22",
    url: "#",
    description: "Step-by-step vector resolution along parallel and perpendicular axis for incline angles θ.",
    assignedTo: ["s1", "s2"],
    downloadsCount: 12,
  },
  {
    id: "mat-3",
    title: "Calculus Quick Reference: Derivatives & Integrals Sheet",
    subject: "Mathematics",
    type: "PDF",
    size: "1.1 MB",
    uploadDate: "2026-08-15",
    url: "#",
    description: "Cheat sheet covering product rule, quotient rule, chain rule, trigonometric identities and common integrals.",
    assignedTo: "ALL",
    downloadsCount: 34,
  },
  {
    id: "mat-4",
    title: "Organic Reaction Mechanisms Visual Roadmap",
    subject: "Chemistry",
    type: "PDF",
    size: "3.8 MB",
    uploadDate: "2026-08-10",
    url: "#",
    description: "Electrophilic substitution, nucleophilic addition, and elimination reaction pathways with color arrows.",
    assignedTo: "ALL",
    downloadsCount: 9,
  },
  {
    id: "mat-5",
    title: "Python Data Structures: Lists, Dictionaries & Binary Trees",
    subject: "Computer Science",
    type: "DOC",
    size: "850 KB",
    uploadDate: "2026-08-05",
    url: "#",
    description: "Clean boilerplate code snippets and time complexity big-O cheat sheet.",
    assignedTo: ["s3"],
    downloadsCount: 7,
  },
];

export const mockSessionReports: SessionReport[] = [
  {
    id: "rep-201",
    sessionId: "sess-103",
    teacherId: "t1",
    studentId: "s3",
    studentName: "Arjun Kumar",
    studentAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    subject: "Mathematics",
    date: "2026-08-27",
    startTime: "02:00 PM",
    endTime: "02:52 PM",
    durationSeconds: 3120,
    durationMinutes: 52,
    topicTaught: "Calculus — Chain Rule & Product Rule Practice",
    topicsCovered: [
      "Composite functions f(g(x))",
      "Trigonometric derivatives (sin, cos, tan)",
      "Product rule quotient transformations",
    ],
    assignmentGiven: "Complete problems 1 through 6 on Calculus worksheet.",
    studentPerformanceRating: 4,
    studentPerformanceNotes: "Arjun demonstrated solid grasp of basic derivatives. Gained confidence handling double chain rules by the end of session.",
    teacherNotes: "Next session will introduce implicit differentiation with circular and elliptic curves.",
    nextSessionPlan: "Implicit Differentiation & Related Rates",
    createdAt: "2026-08-27T15:00:00Z",
  },
  {
    id: "rep-202",
    sessionId: "sess-104",
    teacherId: "t1",
    studentId: "s4",
    studentName: "Meera Thomas",
    studentAvatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80",
    subject: "Mathematics",
    date: "2026-08-25",
    startTime: "05:00 PM",
    endTime: "05:50 PM",
    durationSeconds: 3000,
    durationMinutes: 50,
    topicTaught: "Linear Inequalities & Coordinate Geometry",
    topicsCovered: [
      "Graphing half-planes",
      "Intersection regions for system of inequalities",
      "Distance formula & midpoint theorem",
    ],
    assignmentGiven: "Practice sheet 4 (Questions 1-8)",
    studentPerformanceRating: 5,
    studentPerformanceNotes: "Meera solved all interactive whiteboard problems rapidly without any calculation errors. High retention.",
    teacherNotes: "Ready to advance to quadratic graphing and parabola vertex forms.",
    nextSessionPlan: "Introduction to Quadratic Graphing",
    createdAt: "2026-08-25T17:55:00Z",
  },
];

export const mockNotifications: Notification[] = [
  {
    id: "notif-1",
    userId: "t1",
    targetRole: "TEACHER",
    title: "Assignment Submission",
    message: "Rahul Menon submitted 'Quadratic Equations Mastery'.",
    timestamp: "10 mins ago",
    read: false,
    type: "assignment",
    link: "/teacher/assignments",
  },
  {
    id: "notif-2",
    userId: "t1",
    targetRole: "TEACHER",
    title: "Upcoming 1-on-1 Session",
    message: "Your live session with Rahul Menon starts at 04:00 PM today.",
    timestamp: "1 hour ago",
    read: false,
    type: "session",
    link: "/teacher/sessions",
  },
  {
    id: "notif-3",
    userId: "t1",
    targetRole: "TEACHER",
    title: "Material Downloaded",
    message: "Ananya Nair downloaded 'Mastering Incline Planes'.",
    timestamp: "Yesterday",
    read: true,
    type: "system",
    link: "/teacher/materials",
  },
  {
    id: "notif-4",
    userId: "s1",
    targetRole: "STUDENT",
    title: "Live Class Reminder",
    message: "Live Mathematics session with Alex Thomas starts at 04:00 PM.",
    timestamp: "25 mins ago",
    read: false,
    type: "session",
    link: "/student/sessions",
  },
  {
    id: "notif-5",
    userId: "s1",
    targetRole: "STUDENT",
    title: "Assignment Graded & Feedback",
    message: "Alex Thomas reviewed your Algebra homework. Score: 11/12 (92%).",
    timestamp: "2 hours ago",
    read: false,
    type: "assignment",
    link: "/student/assignments",
  },
];
