"use client";
import Link from "next/link";
import { AppShell } from "@/components/layout/AppShell";
import { useLMS } from "@/lib/store";
export default function Dashboard(){
 const {teachers,students,sessions,assignments,submissions,materials}=useLMS();
 const week=Array.from({length:7},(_,i)=>{const d=new Date();d.setDate(d.getDate()-6+i);const date=d.getFullYear()+"-"+String(d.getMonth()+1).padStart(2,"0")+"-"+String(d.getDate()).padStart(2,"0");return {date,label:d.toLocaleDateString(undefined,{weekday:"short"}),count:sessions.filter(s=>s.date===date&&s.status==="COMPLETED").length};});const max=Math.max(1,...week.map(d=>d.count));
 const subjects=Array.from(new Set(sessions.map(s=>s.subject)));
 return <AppShell><div className="max-w-6xl mx-auto space-y-6"><h1 className="text-2xl font-bold">Platform overview</h1><div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-4">{[["Teachers",teachers.length,"teachers"],["Students",students.length,"students"],["Live classes",sessions.filter(s=>s.status==="LIVE").length,"sessions"],["Assignments / homework",assignments.length,"assignments"]].map(([label,value,path])=><Link key={label} href={"/admin/"+path} className="bg-white border rounded-2xl p-5"><p className="text-slate-500 text-sm">{label}</p><strong className="text-3xl">{value}</strong></Link>)}</div><div className="grid md:grid-cols-2 gap-5"><section className="bg-white border rounded-2xl p-6"><h2 className="font-bold">Completed classes ? last 7 days</h2><div className="h-48 flex gap-4 items-end mt-5">{week.map(d=><div key={d.date} className="flex-1 h-full flex flex-col justify-end items-center gap-2"><span>{d.count}</span><div className="w-full bg-indigo-500 rounded-t" style={{height:(d.count/max*120)+"px"}}/><span className="text-xs">{d.label}</span></div>)}</div></section><section className="bg-white border rounded-2xl p-6 space-y-4"><h2 className="font-bold">Learning activity</h2><p>{submissions.filter(s=>s.status==="REVIEWED").length} submissions graded</p><p>{Math.floor(sessions.filter(s=>s.status==="COMPLETED").reduce((n,s)=>n+(s.actualDurationSeconds||0),0)/3600)} teaching hours completed</p><p>{materials.length} study resources ? {(materials.reduce((n,m)=>n+(m.sizeBytes||0),0)/1048576).toFixed(2)} MB uploaded</p><p>{students.filter(s=>!s.teacherId).length} students awaiting a teacher</p></section></div><section className="bg-white border rounded-2xl p-6 space-y-3"><h2 className="font-bold">Classes by subject</h2>{subjects.length?subjects.map(name=><div key={name} className="flex justify-between"><span>{name}</span><span>{sessions.filter(s=>s.subject===name).length} classes</span></div>):<p className="text-slate-500">Subject activity will appear after classes are scheduled.</p>}</section></div></AppShell>;
}
