"use client";
import Link from "next/link";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { useLMS } from "@/lib/store";
export default function LoginPage() {
 const router=useRouter();const { directory,login,loading,connectionError }=useLMS(); const [role,setRole]=useState<"STUDENT"|"TEACHER">("STUDENT");const [id,setId]=useState("");const [error,setError]=useState("");const [busy,setBusy]=useState(false);
 const people=(role==="TEACHER"?directory.teachers:directory.students).filter(p=>p.status==="active");
 return <main className="min-h-screen grid place-items-center bg-[#f8f9ff] p-6"><form className="bg-white border rounded-3xl p-8 sm:p-12 w-full max-w-lg space-y-6 shadow-sm" onSubmit={async e=>{e.preventDefault();setBusy(true);setError("");try{await login(role,id);router.push(role==="TEACHER"?"/teacher/dashboard":"/student/dashboard");}catch(e){setError(e instanceof Error?e.message:"Unable to continue");}finally{setBusy(false);}}}><Link href="/" className="font-bold text-indigo-600">OneToOne</Link><h1 className="text-3xl font-bold">Your learning workspace</h1><p className="text-slate-500">Choose your role and profile to continue. No password is needed for now.</p><div className="grid grid-cols-2 gap-3">{(["STUDENT","TEACHER"] as const).map(r=><button type="button" key={r} onClick={()=>{setRole(r);setId("");}} className={"rounded-xl p-4 border font-semibold "+(r===role?"bg-indigo-600 text-white":"bg-slate-50")}>{r==="STUDENT"?"Student":"Teacher"}</button>)}</div><label className="block font-medium">Your profile<select required className="mt-2 border rounded-xl p-3 w-full" value={id} onChange={e=>setId(e.target.value)}><option value="">{loading?"Loading profiles?":"Select your name"}</option>{people.map(p=><option key={p.id} value={p.id}>{p.name} ? {p.email}</option>)}</select></label>{!loading&&!people.length&&!connectionError&&<p className="text-slate-500">No profiles yet. Ask an administrator to add you in Manage.</p>}{(error||connectionError)&&<p role="alert" className="text-red-600 text-sm">{error||connectionError}</p>}<button disabled={busy||loading||!id||!!connectionError} className="w-full rounded-xl bg-indigo-600 text-white p-3 font-semibold disabled:opacity-50">{busy?"Opening workspace?":"Continue"}</button><a href="/manage" className="block text-sm text-slate-500">Administrator access</a></form></main>;
}
